apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-app
  template:
    metadata:
      labels:
        app: register-app
    spec:
      containers:
        - name: register-app
          image:  gcr.io/upheld-beach-417514/dm@sha256:1e03771db36fb906edd27da08c2bc373b77068d347837488d28dafc83386a42a
          ports:
            - containerPort: 8090


--- 

apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app 
spec:
  selector:
    app: register-app

  ports:
    - port: 8090
      targetPort: 8090

  type: LoadBalancer
